// Code generated by decorator-gen; DO NOT EDIT.
package decorator

import (
	xx "context"
)

type IncreaseReq struct {
	a   int
	ctx xx.Context
}

type IncreaseResp struct {
	element0 int
	element1 int
}

func IncreaseChan(in chan<- IncreaseReq, out <-chan IncreaseResp) {
	for it := range in {
		element0, element1 := Increase(
			it.a,
			it.ctx,
		)
		out <- IncreaseResp{element0, element1}
	}
}
