// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package template_text

type EmptyString struct{}

func (*EmptyString) Filter(in map[string]string) map[string]string {
	return in
}

type EmptyInt struct{}

func (*EmptyInt) Filter(in map[string]int) map[string]int {
	return in
}
